import type { LearningPath } from '@/types';

export const learningPaths: LearningPath[] = [
  {
    id: 'ai-fundamentals',
    title: 'AI Fundamentals',
    description: 'Master the basics of artificial intelligence',
    overview:
      'A comprehensive introduction to AI concepts, machine learning basics, and neural networks. Perfect for beginners wanting to understand AI foundations.',
    difficulty: 'beginner',
    estimatedHours: 40,
    prerequisites: ['Basic Python', 'High School Mathematics'],
    modules: [
      {
        id: 'ai-basics',
        title: 'What is AI?',
        description: 'Introduction to AI and its applications',
        duration: 5,
        difficulty: 'beginner',
      },
      {
        id: 'ml-intro',
        title: 'Machine Learning Basics',
        description: 'Supervised vs Unsupervised Learning',
        duration: 10,
        difficulty: 'beginner',
      },
      {
        id: 'nn-intro',
        title: 'Neural Networks Introduction',
        description: 'Understanding artificial neural networks',
        duration: 15,
        difficulty: 'beginner',
      },
      {
        id: 'tools-setup',
        title: 'Tools & Environment Setup',
        description: 'Python, TensorFlow, and Jupyter setup',
        duration: 10,
        difficulty: 'beginner',
      },
    ],
    skills: ['Python Basics', 'Math Fundamentals', 'Machine Learning Concepts'],
    targetAudience: 'Complete beginners to AI',
    interests: ['academic', 'practical', 'mixed'],
  },
  {
    id: 'deep-learning',
    title: 'Deep Learning Mastery',
    description: 'Advanced deep learning techniques and applications',
    overview:
      'Dive deep into convolutional neural networks, recurrent neural networks, and transformers. Build production-ready models.',
    difficulty: 'advanced',
    estimatedHours: 80,
    prerequisites: ['AI Fundamentals', 'Python Advanced', 'Linear Algebra'],
    modules: [
      {
        id: 'cnn-deep',
        title: 'Convolutional Neural Networks',
        description: 'CNNs for image processing',
        duration: 20,
        difficulty: 'advanced',
      },
      {
        id: 'rnn-deep',
        title: 'Recurrent Neural Networks',
        description: 'RNNs, LSTMs, and sequence modeling',
        duration: 20,
        difficulty: 'advanced',
      },
      {
        id: 'transformer',
        title: 'Transformers & Attention',
        description: 'Modern transformer architecture',
        duration: 20,
        difficulty: 'advanced',
      },
      {
        id: 'dl-projects',
        title: 'Real-world Projects',
        description: 'Build production deep learning systems',
        duration: 20,
        difficulty: 'advanced',
      },
    ],
    skills: ['Deep Learning', 'Computer Vision', 'NLP', 'PyTorch', 'TensorFlow'],
    targetAudience: 'Intermediate ML practitioners',
    interests: ['practical', 'research', 'mixed'],
  },
  {
    id: 'nlp-journey',
    title: 'Natural Language Processing',
    description: 'Master NLP and language models',
    overview:
      'From tokenization to transformers, learn how to build cutting-edge NLP applications including chatbots and language models.',
    difficulty: 'intermediate',
    estimatedHours: 60,
    prerequisites: ['Python Intermediate', 'Basic Machine Learning'],
    modules: [
      {
        id: 'nlp-basics',
        title: 'NLP Fundamentals',
        description: 'Text processing and tokenization',
        duration: 10,
        difficulty: 'intermediate',
      },
      {
        id: 'embeddings',
        title: 'Word Embeddings',
        description: 'Word2Vec, GloVe, and FastText',
        duration: 12,
        difficulty: 'intermediate',
      },
      {
        id: 'llm-models',
        title: 'Large Language Models',
        description: 'GPT, BERT, and modern LLMs',
        duration: 18,
        difficulty: 'intermediate',
      },
      {
        id: 'nlp-apps',
        title: 'NLP Applications',
        description: 'Sentiment analysis, generation, translation',
        duration: 20,
        difficulty: 'intermediate',
      },
    ],
    skills: ['NLP', 'Text Processing', 'Language Models', 'Python', 'ML'],
    targetAudience: 'ML enthusiasts interested in language',
    interests: ['practical', 'academic', 'entrepreneurship', 'mixed'],
  },
  {
    id: 'practical-ml',
    title: 'Applied Machine Learning',
    description: 'Real-world ML projects and production systems',
    overview:
      'Learn to build, deploy, and maintain ML systems in production. Focus on practical applications and best practices.',
    difficulty: 'intermediate',
    estimatedHours: 50,
    prerequisites: ['Machine Learning Basics', 'Python Proficiency'],
    modules: [
      {
        id: 'data-eng',
        title: 'Data Engineering for ML',
        description: 'Data pipelines and preprocessing',
        duration: 12,
        difficulty: 'intermediate',
      },
      {
        id: 'model-eval',
        title: 'Model Evaluation & Selection',
        description: 'Cross-validation, metrics, hyperparameter tuning',
        duration: 10,
        difficulty: 'intermediate',
      },
      {
        id: 'ml-ops',
        title: 'MLOps & Deployment',
        description: 'Docker, APIs, scaling ML systems',
        duration: 15,
        difficulty: 'intermediate',
      },
      {
        id: 'case-studies',
        title: 'Industry Case Studies',
        description: 'Real projects from tech companies',
        duration: 13,
        difficulty: 'intermediate',
      },
    ],
    skills: ['ML Engineering', 'Data Pipelines', 'Deployment', 'Python', 'MLOps'],
    targetAudience: 'Developers wanting to build ML solutions',
    interests: ['practical', 'entrepreneurship', 'mixed'],
  },
  {
    id: 'computer-vision',
    title: 'Computer Vision Mastery',
    description: 'Advanced vision systems and image processing',
    overview:
      'Master image processing, object detection, segmentation, and facial recognition. Build real-world computer vision applications.',
    difficulty: 'advanced',
    estimatedHours: 70,
    prerequisites: ['Deep Learning Basics', 'Python Advanced'],
    modules: [
      {
        id: 'image-fundamentals',
        title: 'Image Fundamentals',
        description: 'Pixels, filters, and image processing',
        duration: 12,
        difficulty: 'intermediate',
      },
      {
        id: 'object-detection',
        title: 'Object Detection',
        description: 'YOLO, R-CNN, and modern detectors',
        duration: 18,
        difficulty: 'advanced',
      },
      {
        id: 'segmentation',
        title: 'Image Segmentation',
        description: 'Semantic and instance segmentation',
        duration: 16,
        difficulty: 'advanced',
      },
      {
        id: 'cv-projects',
        title: 'Vision Projects',
        description: 'Real-world computer vision applications',
        duration: 24,
        difficulty: 'advanced',
      },
    ],
    skills: ['Computer Vision', 'Deep Learning', 'Image Processing', 'OpenCV', 'PyTorch'],
    targetAudience: 'Advanced ML practitioners in vision',
    interests: ['research', 'practical', 'mixed'],
  },
  {
    id: 'reinforcement-learning',
    title: 'Reinforcement Learning',
    description: 'Learn agents that learn from interaction',
    overview:
      'Master Q-Learning, Policy Gradient, and Actor-Critic methods. Build intelligent agents that learn through interaction.',
    difficulty: 'expert',
    estimatedHours: 90,
    prerequisites: ['Deep Learning', 'Probability & Statistics', 'Advanced Python'],
    modules: [
      {
        id: 'rl-basics',
        title: 'RL Fundamentals',
        description: 'MDPs, rewards, and policies',
        duration: 18,
        difficulty: 'advanced',
      },
      {
        id: 'value-methods',
        title: 'Value-Based Methods',
        description: 'Q-Learning and DQN',
        duration: 22,
        difficulty: 'expert',
      },
      {
        id: 'policy-methods',
        title: 'Policy-Based Methods',
        description: 'Policy Gradient and Actor-Critic',
        duration: 25,
        difficulty: 'expert',
      },
      {
        id: 'rl-applications',
        title: 'Real-World Applications',
        description: 'Robotics, game AI, control systems',
        duration: 25,
        difficulty: 'expert',
      },
    ],
    skills: ['Reinforcement Learning', 'Game AI', 'Control Systems', 'TensorFlow', 'PyTorch'],
    targetAudience: 'Expert ML researchers and engineers',
    interests: ['research', 'practical', 'entrepreneurship'],
  },
  {
    id: 'GenAI',
    title: 'Generative AI & LLMs',
    description: 'Build with modern generative models',
    overview:
      'Learn to work with GPT, Diffusion Models, and other generative systems. Build ChatGPT-like applications and creative AI tools.',
    difficulty: 'intermediate',
    estimatedHours: 55,
    prerequisites: ['NLP Basics', 'Python Intermediate', 'Transformers'],
    modules: [
      {
        id: 'genai-basics',
        title: 'Generative AI Fundamentals',
        description: 'From VAEs to Modern LLMs',
        duration: 12,
        difficulty: 'intermediate',
      },
      {
        id: 'prompt-eng',
        title: 'Prompt Engineering',
        description: 'Techniques and best practices',
        duration: 10,
        difficulty: 'intermediate',
      },
      {
        id: 'llm-fine-tune',
        title: 'Fine-tuning LLMs',
        description: 'Adapt models for specific tasks',
        duration: 15,
        difficulty: 'intermediate',
      },
      {
        id: 'genai-apps',
        title: 'Building GenAI Applications',
        description: 'RAG, agents, and creative tools',
        duration: 18,
        difficulty: 'intermediate',
      },
    ],
    skills: ['Generative AI', 'Prompt Engineering', 'Fine-tuning', 'API Integration', 'Python'],
    targetAudience: 'Developers interested in modern AI',
    interests: ['practical', 'entrepreneurship', 'mixed'],
  },
];
